name: okk
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "https://github.com/The-HellBot/HellBot"
          replace: "https://github.com/TEAM-MISAKA/MISAKA-BOT"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'there was a conflict'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: HellBoy-OP
          commit_user_email: ghosthellboy4@gmail.com
          commit_author: HellBoy-OP <ghosthellboy4@gmail.com>
