name: okk
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@master
        with:
          find: "hell"
          replace: "mikasa"
      - name: Pull All Updates
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'there was a chutiya'
          commit_options: '--no-verify'
          repository: .
          commit_user_name: TEAM-MIKASA
          commit_user_email: sameerpanthi72@gmail.com
          commit_author: TEAM-MIKASA <sameerpanthi72@gmail.com>
